### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by a9k** [h0tw1r3/dvbhdhomerun#6]
Tried your build instructions, got compile error. Looks non-obvious to fix.
```
/usr/bin/make -C build  all
make[2]: Entering directory '/root/src/dvbhdhomerun/userhdhomerun/build'
make[3]: Entering directory '/root/src/dvbhdhomerun/userhdhomerun/build'
make[4]: Entering directory '/root/src/dvbhdhomerun/userhdhomerun/build'
Scanning dependencies of target userhdhomerun
make[4]: Leaving directory '/root/src/dvbhdhomerun/userhdhomerun/build'
make[4]: Entering directory '/root/src/dvbhdhomerun/userhdhomerun/build'
[ 14%] Building CXX object CMakeFiles/userhdhomerun.dir/main.o
[ 28%] Building CXX object CMakeFiles/userhdhomerun.dir/conf_inifile.o
[ 42%] Building CXX object CMakeFiles/userhdhomerun.dir/hdhomerun_control.o
[ 57%] Building CXX object CMakeFiles/userhdhomerun.dir/hdhomerun_controller.o
/root/src/dvbhdhomerun/userhdhomerun/hdhomerun_controller.cpp: In constructor ‘HdhomerunController::HdhomerunController(int)’:
/root/src/dvbhdhomerun/userhdhomerun/hdhomerun_controller.cpp:74:144: error: ‘hdhomerun_discover_find_devices_custom’ was not declared in this scope
 devices_custom(0, HDHOMERUN_DEVICE_TYPE_TUNER, HDHOMERUN_DEVICE_ID_WILDCARD, devices, m_maxDevices);
                                                                                                   ^
CMakeFiles/userhdhomerun.dir/build.make:123: recipe for target 'CMakeFiles/userhdhomerun.dir/hdhomerun_controller.o' failed
make[4]: *** [CMakeFiles/userhdhomerun.dir/hdhomerun_controller.o] Error 1
make[4]: Leaving directory '/root/src/dvbhdhomerun/userhdhomerun/build'
CMakeFiles/Makefile2:91: recipe for target 'CMakeFiles/userhdhomerun.dir/all' failed
make[3]: *** [CMakeFiles/userhdhomerun.dir/all] Error 2
make[3]: Leaving directory '/root/src/dvbhdhomerun/userhdhomerun/build'
Makefile:116: recipe for target 'all' failed
make[2]: *** [all] Error 2
```

**Comment by h0tw1r3** [comment]
Actually, I purposely don't provide build instructions.
Minimal information, such as kernel and distro, are necessary to respond intelligently.
I'm going to assume a local system issue.

**Comment by a9k** [comment]
Running Debian jessie 4.1.0-2-amd64.
The project would be better if the makefile checked the hdhomerun libraries exist.

After compiling hdhomerun's libraries, there is a new error. I do NOT believe this is in your code but something odd in hdhomerun's library. MythTV fails with same error.
```
[ 57%] Building CXX object CMakeFiles/userhdhomerun.dir/hdhomerun_controller.o
/root/src/dvbhdhomerun/userhdhomerun/hdhomerun_controller.cpp: In constructor ‘HdhomerunController::HdhomerunController(int)’:
/root/src/dvbhdhomerun/userhdhomerun/hdhomerun_controller.cpp:74:144: error: ‘hdhomerun_discover_find_devices_custom’ was not declared in this scope
 devices_custom(0, HDHOMERUN_DEVICE_TYPE_TUNER, HDHOMERUN_DEVICE_ID_WILDCARD, devices, m_maxDevices);
                                                                                                   ^
CMakeFiles/userhdhomerun.dir/build.make:123: recipe for target 'CMakeFiles/userhdhomerun.dir/hdhomerun_controller.o' failed
```

Any suggestions would be welcome as hours of searching hdhomerun_discover_find_devices_custom and variations has yielded nothing but a reference to an old bug and the lines of code where it is defined in hdhomerun_discover.c in libhdhomerun.

**Comment by a9k** [comment]
For those that run into this hdhomerun_discover_find_devices_custom error. To fix, I erased all versions of the libhdhomerun.so, pulled the version from github (https://github.com/mharsch/libhdhomerun.git), recompiled and copied that lib to replace the previous one. The latest from HDHomeRun's site is the one that fails. It is a slightly larger lib - about 1K larger.

**Comment by h0tw1r3** [comment]
Glad you figured it out.

> The project would be better if the makefile checked the hdhomerun libraries exist.

The only purpose of this project is to easily create/build a Debian package (which DOES check for the necessary libraries).

If you read up on how to build a package from source (as the README suggests), it would save you a lot of time.

**Comment by a9k** [comment]
Ok. I do know how to build packages and have been doing so since potato. Just saying, it is unusual, these days, to have the requirements only in the package spec.

**Comment by averyfreeman** [comment]
Struggled with this for an hour.  Followed a9k's advice of compiling libhdhomerun.so and replaced in /usr/lib -- did not work.  Also replaced all *.h files in /usr/include/libhdhomerun/ with those newly acquired from git.  Then build completed 3-22-17 Ubuntu 16.10 4.8.0-42-generic SMP x86_64 GNU/Linux -- thought it might help someone else.

**Comment by tysonclugg** [comment]
I figured it out, at least for Ubuntu 16.04. The file `/usr/include/libhdhomerun/hdhomerun_discover.h` in the `libhdhomerun-dev` package includes bindings for `hdhomerun_discover_find_devices_custom_v2`, not `hdhomerun_discover_find_devices_custom` (without the `_v2` postfix).

Looks like a PR is in order...

**Comment by joelmaxuel** [comment]
Hi,
I ran into the same error so I added _v2 to the file make errored out on.  The packages built but now I have this problem (on install):
> Error! Bad return status for module build on kernel: 4.9.0-2-amd64 (x86_64)
I am using Debian stretch.  Full log is below.  Thank you.
https://pastebin.com/c9gYh2rg

**Comment by a9k** [comment]
Looks like you're missing the DVB-core header files. The compile is failing trying to find header files like dvbdev.h. I'm using deb http://www.deb-multimedia.org unstable main non-free
That may make a difference.

**Comment by fragginright** [comment]
installing the libhomerun suggested by a9k almost fixes things for me. still have one error 



```
[100%] Linking CXX executable userhdhomerun
CMakeFiles/userhdhomerun.dir/hdhomerun_controller.o: In function `HdhomerunController::HdhomerunController(int)':
hdhomerun_controller.cpp:(.text+0x687): undefined reference to `hdhomerun_discover_find_devices_custom'
collect2: error: ld returned 1 exit status
CMakeFiles/userhdhomerun.dir/build.make:250: recipe for target 'userhdhomerun' failed
make[4]: *** [userhdhomerun] Error 1
make[4]: Leaving directory '/home/matt/dvbhdhomerun/userhdhomerun/build'
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/userhdhomerun.dir/all' failed
make[3]: *** [CMakeFiles/userhdhomerun.dir/all] Error 2
make[3]: Leaving directory '/home/matt/dvbhdhomerun/userhdhomerun/build'
Makefile:127: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/matt/dvbhdhomerun/userhdhomerun/build'
Makefile:32: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/matt/dvbhdhomerun/userhdhomerun'
debian/rules:17: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
```
