### ISSUE TITLE
unable to get this to build on ubuntu 16.04

### ISSUE THREAD

**Issue by fragginright** [h0tw1r3/dvbhdhomerun#10]
```
[ 50%] Building CXX object CMakeFiles/userhdhomerun.dir/hdhomerun_controller.o
/home/matt/dvbhdhomerun/userhdhomerun/hdhomerun_controller.cpp: In constructor ‘HdhomerunController::HdhomerunController(int)’:
/home/matt/dvbhdhomerun/userhdhomerun/hdhomerun_controller.cpp:74:144: error: ‘hdhomerun_discover_find_devices_custom’ was not declared in this scope
   int numOfDevices = hdhomerun_discover_find_devices_custom(0, HDHOMERUN_DEVICE_TYPE_TUNER, HDHOMERUN_DEVICE_ID_WILDCARD, devices, m_maxDevices);
                                                                                                                                                ^
CMakeFiles/userhdhomerun.dir/build.make:134: recipe for target 'CMakeFiles/userhdhomerun.dir/hdhomerun_controller.o' failed
make[4]: *** [CMakeFiles/userhdhomerun.dir/hdhomerun_controller.o] Error 1
make[4]: Leaving directory '/home/matt/dvbhdhomerun/userhdhomerun/build'
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/userhdhomerun.dir/all' failed
make[3]: *** [CMakeFiles/userhdhomerun.dir/all] Error 2
make[3]: Leaving directory '/home/matt/dvbhdhomerun/userhdhomerun/build'
Makefile:127: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/matt/dvbhdhomerun/userhdhomerun/build'
Makefile:32: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/matt/dvbhdhomerun/userhdhomerun'
debian/rules:17: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
```
